.\" Copyright (c) 1998 James P. Howard, II <jh@jameshoward.us>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd July 10, 1998
.Dt RPT 1 LOCAL
.Sh NAME
.Nm rpt
.Nd "run a process repeatedly"
.Sh SYNOPSIS
.Nm rpt
.Op Fl n Ar iterations
.Op Fl s Ar seconds
.Ar program options
.Sh DESCRIPTION
.Nm Rpt
will run a given program 
.Op Ar iterations , 
once every
.Ar seconds
seconds.  It is designed to show the changing output of a command over
time.
The following options are recognized.
.Bl -tag -width 8n
.It Fl n Ar iterations
Run 
.Ar program
.Ar iterations 
number of times, defaults to infinety.
.It Fl s Ar seconds
Run
.Ar program
once every
.Ar seconds 
seconds, defaults to two.
.El
.Sh HISTORY
This command is based on a similar command by the name of 
.Nm watch
from Pyramid OSx.
.Sh BUGS
Completely and totally incompatible with the command by the name of 
.Nm watch
from Pyramid OSx.
.Sh WEBSITE
For more information, please see 
.Ar http://github.com/howardjp/rpt .
.Sh SEE ALSO
.Xr sleep 1
